rbccps-iisc/ideam

modules/install.py
middleware.conf will mention for all Linux distributions as "linux" instead of ubuntu.
=> Fix: change OS from ubuntu to linux

README.md
* Fix smart city rbccps page URL.
* Provide an example of the middleware usage.
=> Update: README with ansible installation

README.md
Mention dns isssue in README.md
Mention --bip requirement
Mention firewall issue
=> Fix: mention linux issues in README.md

modules/start.py
=> Fix: create new hosts file for start command with limit

config/hypercat/create_db.js, install.yaml
* catdemo db is not created during the cat server installation
=> Fix: catalogue POST failure

tests/test_setup.sh
Test setup does not require swap creation if there is enough RAM (8G) available.
=> Fix: avoid swap creation for test setup

README.rst
* Specify DNS options based on init used (SysV and systemd)
* Default middleware port changed to 10443
=> Update Readme to version 0.1.0 release

README.rst
* content-type was missing which caused the register API to fail
=> Fix: missing content-type: application/json

images/Dockerfile.ubuntu, images/Dockerfile.ubuntu.certified.elk, images/Dockerfile.ubuntu.certified.kong
elastic search container seems failing during the installation (due to old ubuntu image).
=> Fix: elk container creation failures

install_idps_travis.yml, modules/start.py
Bugfix: Reordered tasks in ansible playbook
Signed off by: Poorna Chandra Tejasvi<pct960@gmail.com>
=> Integrated IDPS setup with IDEAM installation

modules/create_hosts.py, start.yaml
Steps:
1. Start php
2. Start backend
3. Start frontend
=> video: added start script to start videoserver

config/idps/metering_cron.py
Signed off by: Poorna Chandra Tejasvi <pct960@gmail.com>
=> Feature: Time based metering complete

install.yaml
Signed off by: Manoj Kumar <kmanoj1363@gmail.com>
=> Bugfix: Ignoring rsyslogd errors

config/kong/handler-alpine.lua, install.yaml, modules/download_packages.py, modules/quick_install.py, tasks/elasticsearch/quick-elk-setup.sh, tasks/elasticsearch/quick-elk.sh, tasks/hypercat/quick-catalogue-setup.sh, tasks/hypercat/quick-catalogue.sh, tasks/kong/quick-kong-setup.sh, tasks/kong/quick-kong.sh, tasks/ldapd/quick-ldapd-setup.sh, tasks/ldapd/quick-ldapd.sh, tasks/rabbitmq/quick-rmq-setup.sh, tasks/tomcat/quick-tomcat-setup.sh
Signed off by: Poorna Chandra Tejasvi <pct960@gmail.com>
=> WIP: Pub/Sub with quick install ready

.travis.yml, ideam.py, modules/quick_install.py, tasks/elasticsearch/quick-elk-setup.sh, tasks/elasticsearch/quick-elk.sh, tasks/hypercat/quick-catalogue-setup.sh, tasks/hypercat/quick-catalogue.sh, tasks/kong/quick-kong-setup.sh, tasks/kong/quick-kong.sh, tasks/ldapd/quick-ldapd-setup.sh, tasks/ldapd/quick-ldapd.sh, tasks/rabbitmq/quick-rmq-setup.sh, tasks/rabbitmq/quick-rmq.sh, tasks/tomcat/quick-tomcat.sh, tests/catalogue.sh, tests/create_entity.sh, tests/database.sh, tests/deregister.sh, tests/deregister1.sh, tests/publish.sh, tests/share.sh, tests/subscribe.sh, tests/test_setup.sh
WIP: Videoserver needs to be included in quick install
Feature: Updated Travis and test scripts
Signed off by: Poorna Chandra Tejasvi <pct960@gmail.com>
=> Feature: Added quick install feature to IDEAM

ideam.py, modules/quick_install.py, tasks/elasticsearch/quick-elk-setup.sh, tasks/elasticsearch/quick-elk.sh, tasks/hypercat/quick-catalogue-setup.sh, tasks/hypercat/quick-catalogue.sh, tasks/kong/quick-kong-setup.sh, tasks/kong/quick-kong.sh, tasks/ldapd/quick-ldapd-setup.sh, tasks/ldapd/quick-ldapd.sh, tasks/rabbitmq/quick-rmq-setup.sh, tasks/rabbitmq/quick-rmq.sh, tasks/tomcat/quick-tomcat-setup.sh, tasks/tomcat/quick-tomcat.sh, tasks/videoserver/quick-vs-setup.sh, tasks/videoserver/quick-vs.sh
Feature: Added --limit option
Feature: Added display messages for setup tasks
=> Temporarily removed CA container

ideam.py, modules/install.py, modules/quick_install.py, modules/quickstart.py, tasks/kong/quick-kong-setup.sh, tasks/kong/quick-kong.sh, tests/catalogue.sh, tests/create_entity.sh, tests/database.sh, tests/deregister.sh, tests/deregister1.sh, tests/publish.sh, tests/share.sh, tests/subscribe.sh
Kong port forwarded to port 80
=> Added limit option for quickstart

.gitignore, build/debian/control, ideam.conf, modules/install.py, shells/catalogue, shells/elasticsearch, shells/kong, shells/ldapd, shells/rabbitmq, shells/tomcat, shells/videoserver
Added shell scripts for access to containers
=> Minor bugfixes

ideam.py, modules/install.py, modules/start.py, tasks/catalogue/start.sh, tasks/videoserver/install.sh
Mapped appropriate volumes for containers
=> Fixed bug in start script

modules/install.py, tests/catalogue.sh, tests/create_entity.sh, tests/database.sh, tests/deregister.sh, tests/deregister1.sh, tests/publish.sh, tests/share.sh, tests/subscribe.sh
=> Added docker volumes

ideam.py, modules/generate_password.py, modules/install.py, ubuntu/config/kong/share.py, ubuntu/config/kong/share_new.py
Using temp files for ldap commands
Patched code to prevent command injections
=> Updated subscribe API to include message info

build/build.sh, ideam.py, modules/install.py, modules/start.py, tests/delete.sh
Fixed bug in start script
Made exchange to queue bindings durable
=> Middleware restart is now durable

ideam.conf, ideam.py, modules/generate_password.py, modules/install.py, shells/apigateway, shells/kong, tasks/apigateway/install.sh, tasks/apigateway/start.sh, tasks/broker/start.sh, tests/test_setup.sh
Added missing volume mappings in docker
=> Cleaned up codebase

install, modules/install.py, start, tasks/apigateway/setup.sh
Fixed bug in deregister script
Fixed bug in Kong setup script
=> Using global connection pools

config/broker/rabbitmq.config, tasks/broker/setup.sh
Restructured LDAP
Updated Follow, Share and Bind APIs to accomodate LDAP changes
=> Bugfix: Inter-device writes now possible

modules/setup.py, tasks/elasticsearch/install.sh, tasks/webserver/database_setup.sh, tasks/webserver/database_start.sh, tasks/webserver/setup.sh, tasks/webserver/start.sh
Adding CDX Database-Connector for elasticsearch
Removed logstash dependency and startup from CDX
Updated webserver startup during installation and Adding CDX Database-Connector jar
=> Database connector for broker database queue to database
